# Generated by Django 3.2 on 2021-04-15 03:37

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('business_name', models.CharField(default=None, max_length=64)),
                ('date_joined', models.DateTimeField()),
                ('address', address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('managers', models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('discount_ratio', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('business', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('quantity_in_stock', models.DecimalField(decimal_places=6, default=None, max_digits=10)),
                ('unit', models.CharField(default='pc', max_length=3, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('currency', models.CharField(default='dollar', max_length=3, null=True)),
                ('business', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(null=True)),
                ('date_due', models.DateField(null=True)),
                ('terms', models.CharField(choices=[('COD', 'Cash on delivery'), ('CIA', 'Cash in advance'), ('NET7', 'Net 7 days'), ('NET10', 'Net 10 days'), ('NET30', 'Net 30 days'), ('NET60', 'Net 60 days'), ('NET90', 'Net 90 days'), ('NET120', 'Net 120 days')], default='NET30', max_length=24, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('currency', models.CharField(default='dollar', max_length=3, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('bill_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_from', to='timelyapp.business')),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_to', to='timelyapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.DecimalField(decimal_places=6, max_digits=10)),
                ('item_total_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('discount_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.discount')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='timelyapp.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelyapp.inventory')),
            ],
        ),
    ]
