# Generated by Django 3.2 on 2021-04-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
