# Generated by Django 3.1.4 on 2021-03-16 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default=None, max_length=64)),
                ('address', models.CharField(default=None, max_length=64)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(null=True)),
                ('is_from_member', models.BooleanField(default=False)),
                ('is_to_member', models.BooleanField(default=False)),
                ('bill_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_from', to='timelyapp.business')),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_to', to='timelyapp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=10)),
                ('unit', models.CharField(default=None, max_length=3, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelyapp.business')),
            ],
        ),
    ]
