# Generated by Django 3.2 on 2021-04-15 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0002_alter_business_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='managers',
            field=models.ManyToManyField(default=None, null=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
