# Generated by Django 3.1.4 on 2021-03-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0002_business_inventory_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('discount_ratio', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.DecimalField(decimal_places=6, max_digits=10)),
                ('item_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelyapp.discount')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelyapp.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelyapp.inventory')),
            ],
        ),
    ]
