# Generated by Django 3.2 on 2021-05-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0003_alter_inventory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=6, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
