# Generated by Django 3.1.4 on 2021-03-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0003_auto_20210316_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('COD', 'Cash on delivery'), ('CIA', 'Cash in advance'), ('NET7', 'Net 7 days'), ('NET10', 'Net 10 days'), ('NET30', 'Net 30 days'), ('NET60', 'Net 60 days'), ('NET90', 'Net 90 days'), ('NET120', 'Net 120 days')], default='NET30', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_ratio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
    ]
