# Generated by Django 3.2 on 2021-05-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0004_order_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='unit_price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_price',
            new_name='invoice_total_price',
        ),
    ]
