# Generated by Django 3.1.4 on 2021-03-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0004_auto_20210329_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.discount'),
        ),
    ]
