# Generated by Django 3.2 on 2021-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0004_auto_20210415_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='currency',
            field=models.CharField(default='USD', max_length=3, null=True),
        ),
    ]
