# Generated by Django 3.2 on 2021-04-18 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_auto_20210415_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='managers',
            field=models.ManyToManyField(default=None, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
