# Generated by Django 3.1.4 on 2021-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_auto_20210330_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='currency',
            field=models.CharField(default='dollar', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='pc', max_length=3, null=True),
        ),
    ]
