# Generated by Django 3.2 on 2021-05-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_auto_20210507_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_price',
            new_name='unit_price',
        ),
    ]
