# Generated by Django 3.1.4 on 2021-03-30 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0006_auto_20210330_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
