# Generated by Django 3.2 on 2021-05-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0006_rename_item_price_inventory_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='unit_price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='unit',
            new_name='item_unit',
        ),
    ]
