# Generated by Django 3.1.4 on 2021-03-30 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0007_auto_20210330_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='managers',
        ),
        migrations.AddField(
            model_name='business',
            name='manager',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
