# Generated by Django 3.1.4 on 2021-03-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0008_auto_20210330_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='manager',
            new_name='managers',
        ),
    ]
