# Generated by Django 3.2 on 2021-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0008_auto_20210511_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='currency',
            field=models.CharField(default='USD', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=6, null=True),
        ),
    ]
