# Generated by Django 3.2 on 2021-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0009_auto_20210512_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='key',
            field=models.CharField(default='p!OOR&E[WnxP(o6?p~m$AOi1d]Gc_`', max_length=64),
        ),
    ]
