# Generated by Django 3.1.4 on 2021-03-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0011_auto_20210330_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_due',
            field=models.DateField(null=True),
        ),
    ]
