# Generated by Django 3.1.4 on 2021-03-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0012_invoice_date_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='order_id',
            new_name='purchase_order',
        ),
    ]
