# Generated by Django 3.1.4 on 2021-03-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0014_auto_20210330_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='dollar', max_length=3, null=True),
        ),
    ]
