# Generated by Django 3.1.4 on 2021-03-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0015_invoice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_from_member',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_to_member',
        ),
        migrations.AddField(
            model_name='business',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
