# Generated by Django 3.1.4 on 2021-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0016_auto_20210330_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
