# Generated by Django 3.1.4 on 2021-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0018_auto_20210331_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
