# Generated by Django 3.1.4 on 2021-03-31 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0021_auto_20210331_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_items', to='timelyapp.invoice'),
        ),
    ]
