# Generated by Django 3.1.4 on 2021-04-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0022_auto_20210331_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrder',
            new_name='Order',
        ),
    ]
