# Generated by Django 3.1.4 on 2021-04-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0023_auto_20210402_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='subtotal_price',
        ),
    ]
