# Generated by Django 3.1.4 on 2021-04-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0024_auto_20210402_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal_price',
            new_name='item_total_price',
        ),
    ]
