# Generated by Django 3.1.4 on 2021-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0025_auto_20210402_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(default='NONE', max_length=100, null=True),
        ),
    ]
