# Generated by Django 3.1.4 on 2021-04-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0026_auto_20210402_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.discount'),
        ),
    ]
