# Generated by Django 3.1.4 on 2021-04-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0027_auto_20210402_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='business',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.business'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='business',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelyapp.business'),
        ),
    ]
