# Generated by Django 3.1.4 on 2021-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0028_auto_20210402_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
