# Generated by Django 3.2 on 2021-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0031_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(null=True),
        ),
    ]
