# Generated by Django 3.2 on 2021-04-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0033_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
    ]
