# Generated by Django 3.2 on 2021-04-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0034_remove_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
