# Generated by Django 3.2.4 on 2021-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
