# Generated by Django 3.2.9 on 2022-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_tax',
            new_name='invoice_tax_amt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_tax_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='item_tax_rates',
            field=models.ManyToManyField(default=None, null=True, related_name='item_taxes', to='timelyapp.Taxes'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='abbreviation',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
