# Generated by Django 3.2.4 on 2021-09-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='timelyapp.business'),
        ),
    ]
