# Generated by Django 3.2.4 on 2021-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0002_auto_20210709_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='stripe_id',
            new_name='stripe_act_id',
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_cus_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
