# Generated by Django 3.2.9 on 2022-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0002_alter_order_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='compound',
            field=models.BooleanField(default=False),
        ),
    ]
