# Generated by Django 3.2.4 on 2021-09-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0002_auto_20210905_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='timelyapp.business'),
        ),
    ]
