# Generated by Django 3.2.7 on 2021-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0003_alter_customuser_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_purchased',
            field=models.IntegerField(),
        ),
    ]
