# Generated by Django 3.2.4 on 2021-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0003_auto_20210726_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stripe_def_pm',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
