# Generated by Django 3.2.9 on 2022-01-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0003_alter_taxes_compound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='city',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='country',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='state',
        ),
        migrations.RemoveField(
            model_name='taxes',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='deleted_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='taxes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
