# Generated by Django 3.2.4 on 2021-08-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0004_business_stripe_def_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='stripe_def_pm',
        ),
    ]
