# Generated by Django 3.2.4 on 2021-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_remove_business_stripe_def_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_purchase',
            field=models.DateField(null=True),
        ),
    ]
