# Generated by Django 3.2.9 on 2022-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_auto_20220107_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
