# Generated by Django 3.2.9 on 2021-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0005_invoice_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_tax_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
