# Generated by Django 3.2.4 on 2021-08-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0006_auto_20210803_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='fax',
            new_name='business_fax',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='phone',
            new_name='business_phone',
        ),
    ]
