# Generated by Django 3.2.4 on 2021-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0007_auto_20210811_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SALES STAFF', 'Can view receivables only'), ('PURCHASING STAFF', 'Can view payables only'), ('STAFF', 'Can view all invoices, but only view'), ('SALES MANAGER', 'Can generate invoices / approve purchase orders'), ('PURCHASING MANAGER', 'Can approve invoices / generate purchase order'), ('MANAGER', 'Full access to payables and receivables'), ('CONTROLLER', 'Full access to payables/receivables and can change user permissions'), ('OWNER', 'Full access, irrevocable')], default='STAFF', max_length=64, null=True),
        ),
    ]
