# Generated by Django 3.2.9 on 2022-01-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0007_order_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_price',
            new_name='unit_price',
        ),
    ]
