# Generated by Django 3.2.9 on 2021-12-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0008_taxes_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='created_by',
            new_name='business',
        ),
    ]
