# Generated by Django 3.2.9 on 2021-12-17 02:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0009_rename_created_by_taxes_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
