# Generated by Django 3.2.4 on 2021-08-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0010_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SALES STAFF', 'Sales Staff can view receivables only'), ('PURCHASING STAFF', 'Purchasing Staff can view payables only'), ('STAFF', 'Staff can view all invoices, but only view'), ('SALES MANAGER', 'Sales Manager can generate invoices / approve purchase orders'), ('PURCHASING MANAGER', 'Purchasing Manager can approve invoices / generate purchase order'), ('MANAGER', 'Manager has full access to payables and receivables'), ('CONTROLLER', 'Controller has full access to payables/receivables and can change user permissions'), ('OWNER', 'Owner has full access and is irrevocable')], default='OWNER', max_length=64, null=True),
        ),
    ]
