# Generated by Django 3.2.9 on 2021-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0010_alter_taxes_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financing_request',
            field=models.BooleanField(default=False),
        ),
    ]
