# Generated by Django 3.2.9 on 2021-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0011_invoice_financing_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_total_tax',
            new_name='invoice_tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
