# Generated by Django 3.2.9 on 2021-12-17 19:19

import customshortuuidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0012_auto_20211217_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='financing_request',
        ),
        migrations.CreateModel(
            name='FinancingRequests',
            fields=[
                ('id', customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PAYOUT', 'Immediate Payment'), ('PAYLATER', 'Buy now pay later')], default='CA', max_length=24)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_business', to='timelyapp.business')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='timelyapp.invoice')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reqest_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
