# Generated by Django 3.2.9 on 2021-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0013_auto_20211217_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financingrequests',
            name='type',
        ),
        migrations.AddField(
            model_name='financingrequests',
            name='financing_type',
            field=models.CharField(choices=[('PAYOUT', 'Immediate Payment'), ('PAYLATER', 'Buy now pay later')], default=None, max_length=24),
        ),
    ]
