# Generated by Django 3.2.9 on 2021-12-17 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0014_auto_20211217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingrequests',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_biz', to='timelyapp.business'),
        ),
        migrations.AlterField(
            model_name='financingrequests',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_invoice', to='timelyapp.invoice'),
        ),
        migrations.AlterField(
            model_name='financingrequests',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
