# Generated by Django 3.2.4 on 2021-08-30 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0014_remove_invoice_recent_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('business_name', models.CharField(default=None, max_length=64, null=True)),
                ('employees', models.CharField(choices=[('1-10', '1-10'), ('11-30', '11-30'), ('31-50', '31-50'), ('51-100', '51-100'), ('100+', '100+')], default=None, max_length=24, null=True)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('MANAGER', 'Management'), ('OWNER', 'Business owner')], default=None, max_length=24, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
