# Generated by Django 3.2.4 on 2021-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0017_auto_20210903_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='biz_HKWJKTf8WANAsUqNGexw3C', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='usr_HaMfLeB26mdoyLDwUm5Uy2', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(default='itm_4jpFbLvRVndXa95UR8moHg', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='inv_3aTtrqbSuwCVeQuTJiXbs6', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='ord_LsLjFRrFMSD7n4oU8zMFXv', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
