# Generated by Django 3.2.4 on 2021-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0018_auto_20210903_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='biz_bqRhNHakTdJBwYnc7ySa4F', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='usr_d33xa52ZHgmTsqg72zzQLm', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(default='itm_ZwUn6WzAwKkgq58r4Ub9rM', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='inv_kgStobvyjrCU7P7kv2g4rJ', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='ord_TYWYQe4hHahW8a2p7De5f6', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
