# Generated by Django 3.2.4 on 2021-09-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0019_auto_20210903_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='biz_j2itoKsv2W7aMV2JWqfmkg', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='usr_cSg8VFVUnUfhYeCh4xUQuY', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(default='itm_Ept3Z7jeAXdXyk8jeo9TbW', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='inv_BHQoCbHbhSJyiXk2yUnJVj', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='ord_2C2m7AL2uXTwLsqQGrfz3Q', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
