# Generated by Django 3.2.4 on 2021-09-04 01:57

import customshortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0020_auto_20210903_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.CharField(default='biz_HrE5VkDcfr4CCLUHdmjQZi', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='usr_NoDN42JdkLV3F9sg5LFpV4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(default='itm_SBS8BMfLJLd3s5k2sXGni9', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='ord_mkf9PV7i8WL25SEUWEZyAt', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
