# Generated by Django 3.2.4 on 2021-09-04 02:04

import customshortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0021_auto_20210903_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='usr_cQ4zDJ5s6eqY2kHKXxhBq6', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=customshortuuidfield.fields.CustomShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
